### ISSUE TITLE
modus pagination

### ISSUE THREAD

**Issue by anamarquezz** [trimble-oss/modus-web-components#1045]
Modus-Pagination Properties

I have some issues with modus pagination using the component in this way

`<modus-pagination [activePage]="activePage"  [minPage]="minPage" [maxPage]=maxPage [size]=pagination.size (pageChange)="ChangePagination($event)"></modus-pagination>`

im just testing with this calculations:

```ts
 ChangePagination(e: Event): void {
    let page =  (e as CustomEvent).detail;
    console.log(page);
    this.performePagination(page)
  }

  performePagination(page: number): void {
     // this.pagination.hasPagination= false;
      let offset = (page - 1) * this.sizeTable;
      this.data =  this.auxData.slice(offset).slice(0, this.pagination.sizeTable);
      this.pagination.currentPage = page;
      this.activePage = page;
      this.maxPage = Math.ceil(this.auxData.length / this.pagination.sizeTable);
      this.minPage = 1;
      this.hasPagination = this.maxPage ===1 ? false : true;
}
     
```

but i have this problem that is shows me this page numbers, and the  Left abd Right Chevron are not showing
![image](https://user-images.githubusercontent.com/12877909/220485907-4d234d37-948e-4a8d-bae4-afb3486d19c0.png)

**Comment by anamarquezz** [comment]
![image](https://user-images.githubusercontent.com/12877909/220487384-703a7a02-2968-4ef5-9f5b-625d6a7f5836.png)

**Comment by coliff** [comment]
I think it's because you only have 3 pages so the chevrons don't show. You can test this in the 'Canvas' tab: https://modus-web-components.trimble.com/?path=/story/components-pagination--default&args=activePage:2;maxPage:3;size:large

![image](https://user-images.githubusercontent.com/1212885/220487896-f5568d51-4eaa-402b-a214-3f3b1244b27f.png)

Perhaps we could add option to always display next/previous chevrons for pagination controls.

**Comment by anamarquezz** [comment]
I see, thank you so much 😃
