### ISSUE TITLE
Modus NavBar - Include Add icon

### ISSUE THREAD

**Issue by cjwinsor** [trimble-oss/modus-web-components#1247]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Proposal

Include the Add icon in the NavBar component.

![image](https://user-images.githubusercontent.com/1130129/235176587-27cc9052-593d-48f4-8ea7-a884e0605466.png)

It is e-Builder's intent to work on this request.

### Motivation and context

This would be leveraged to provide quick add functionality.  This would enable our clients to always have access to our quick add feature in a convenient location.

### Which npm package?

@trimble-oss/modus-web-components

### Priority

Medium

### What is the product name the feature is requested for?

e-Builder

### What is the team name the product belongs to?

e-Builder

### What is the division name the team belongs to?

e-Builder

**Comment by cjwinsor** [comment]
# NavBar - Add Button Proposal

## Requirements
An Add button added to `NavBar` to support e-Builder’s Quick Add functionality
Add button, when clicked, can show content provided through the implementation

This is one of 2 icons that the e-Builder product is looking to add.
## Original Implementation
The original design added the `Add` icon using the same pattern as the other icons. A `show-add` prop was added to the `ModusNavbar` component along with an accompanying `addMenuOpen` event.

It was requested that an alternative approach be created to better support product specific use cases.  

## Alternative Suggestion
A collection is provided that defines icons to insert into the `NavBar`. The following schema is suggested:
```
// An array of items with this definition at minimum
{
  id: string;
  label string;
  icon: string;
}
```
A label property for tooltips (another issue we are working on), can be omitted until that work is done.
An icon property can function like the `SideNav` items that accepts either a built-in icon or an image url.

For slots, we can either request the use of `<div slot="{id}"></div>` or request the slot name be provided. A generic wrapper component can be created to wrap a `<slot name="{id}"></slot>`. This could also replace the existing notifications menu component.

And finally, something like `navItemClick` or `navItemOpen` event.

## Considerations
1. Should there be a limit to the number of icons? e-Builder will need potentially 3 icons (Add, Reports, Accessibility... not sure if finalized). If considered, can limiting the amount be considered outside the scope of this work?
2. Do we only one to support built in icons, so nothing crazy gets added to the `NavBar`, or is that too restrictive?
3. Should there be more control on placement?  We are looking to have these icons after the `search` icon.
4. Would there be any desire to have some or all of the existing icons (except profile) use this mechanism?  Such as the pendo placeholder, which is outside the current default specification for modus as well.  If considered, can this be outside the scope of this work?

**Comment by msankaran0712** [comment]
cc @coliff @ryan-henness-trimble 
hey @cjwinsor I love the idea of passing an array for navbar icons. 

1. Anything in the below-highlighted group is optional and any team can choose to add or change the order of the elements. So the array configuration will be useful and it can prevent adding separate configurations for tooltips.
![image](https://user-images.githubusercontent.com/50131391/236251714-482055fa-6cbe-4f3d-81c6-50ceac965854.png).
My only concern is the existing icons notifications and help, also are optional and I would recommend those to be part of the array too.

2.  I think it is okay to not limit the icons at the moment and it's better to accept both the icon name and the icon URL because the existing Modus icons set(https://modus-icons.trimble.com/) is huge and I don't know whether all those icons will be made available inside web components.

3. I talked to @egunther39  about the placements and you are right about the search icon. Where did you find the text  "...any additional buttons should be placed in-between Search and Notifications"  ?

**Comment by cjwinsor** [comment]
@msankaran0712 That line about placement was on the [Design System Page](https://modus.trimble.com/components/web/navbars/styles/#specifications).  

I later saw that the responsive design details indicates the expectation for collapsing the icons, so in theory the count shouldn't matter as long as we implement some collapsing ability when responsiveness is added.

Notifications, Help, and maybe even the pendo placeholder, could be handled in the array.  That could be additional scope later as a planned deprecation, or we could remove them as a breaking change as part of this work.

Any thoughts or suggestions on the name of the array?  

Let me know when we are good to start on this change and we'll get it going asap.

**Comment by msankaran0712** [comment]
It is safe to remove the pendo placeholder. 
I suggest we remove notifications and help and add them to the array now, it has to be done sooner or later. 
@ryan-henness-trimble Please let us know if you think otherwise. 

There is no other reason for delaying this work, once @ryan-henness-trimble confirms we should be good to start :)

For the array's name, maybe `items`. Please proceed with whatever name you think is appropriate for now.

**Comment by ryan-henness-trimble** [comment]
The Pendo placeholder is good to remove 👍 

I like the alternative of passing in the icons as a collection. Here are some schema considerations I thought of:
```js
{
  id: string;
  tooltip: string; // Renamed 'label'
  icon: string;
  orderIndex: number; // Details the position of the icon (so that it is more explicit than array order)
  priority: number; // Details the priority level for responsive collapsing
  menu?: 'pop-out' | 'left-side-bar' | 'right-side-bar' | undefined; // The menu type (if left null/undefined, no menu is provided)
  disabled: boolean; // Whether the icon is disabled
}
```

Regarding
> I think it is okay to not limit the icons at the moment and it's better to accept both the icon name and the icon URL because the existing Modus icons set (https://modus-icons.trimble.com/) is huge and I don't know whether all those icons will be made available inside web components.

As a consumer, I would expect all of the Modus icons to be available through this dynamic collection passed into the navbar. We should consider adding an issue to get the icons added to the `IconMap`, or possibly consume the `@trimble-oss/modus-icons` package

**Comment by cjwinsor** [comment]
We are going to move forward with the following schema for now
```ts
{
  id: string;
  tooltip: string; // Renamed 'label'
  icon: string;
  orderIndex: number; // Details the position of the icon (so that it is more explicit than array order)
  menu?: 'pop-out' | undefined;
}
```

We'll we leaving the existing icons to be deprecated later. We will use the location we had the + icon added as our location to insert in new icons for now.  A new component will be created as well which will serve as a generic pop-out container.

**Comment by msankaran0712** [comment]
@cjwinsor Closing the issue as we have merged the PR
