### ISSUE TITLE
Bigger tap target for resizing columns in a table

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#1973]
E-Builder request from Teja: 

Currently, the touch target for resizing columns is very precise, which could create issues for people with dexterity problems. Suggestion: we should add some padding on both sides of the column line (4px on each side for a tap target of 8px).

**Comment by cjwinsor** [comment]
@apaddock I will say that the trick I used in e-Builder to create the resize handler (in planning module) was to set `position: absolute; float: right; z-index:200; right:-3px; width: 7px` on the drag handler.

This allows the drag handler to be overtop the border instead of strictly beside it within the header completely.  What I don't enjoy about most resize handlers is that I expect to be able to drag the border but can't and have to move my mouse over to the left at least a pixel in order to get the handler.  The above solved for that.  There may be more modern ways to do the same thing.  I'd be curious if something like this can be implemented, as it would create a larger target and a more intuitive one.  

![DragHandlerEB](https://github.com/trimble-oss/modus-web-components/assets/1130129/3607d468-a757-4238-b3b7-c5913a8e78ed)

Size note: used `cursor: w-resize;` instead of `cursor: col-resize;` because back when this was written `col-resize` wasn't supported everywhere.
