### ISSUE TITLE
Enforce Node/NPM versions in package.json

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-web-components#455]

**Comment by coliff** [comment]
I think we should add this:

```json
  "engines": {
    "node": ">=14",
    "npm": ">=7"
  },
```

- [Node v14 is the earliest supported/maintained version](https://nodejs.org/en/about/releases/).
- [npm v7 and later changed the package-lock format from 1 to 2](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json#handling-old-lockfiles) so it's good to require at least v7 in order to avoid package-lock changes if someone is using npm v6.

**Comment by coliff** [comment]
let me know if you agree @ryan-henness-trimble - you can either make this change yourself or I can do it in a PR tomorrow.

**Comment by ryan-henness-trimble** [comment]
Ooo nice, I can make this change

**Comment by coliff** [comment]
ok cool - do it for Stencil-workspace for sure...

For Angular-workspace we shouldn't require npm 7 or higher right now because that has package-lock v1. So that should be updated to v2 first.
